import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:tandem/app.dart';
// firebase_options_<env>.dart files are generated by `flutterfire configure`
// per environment. For now we ship a placeholder that the user must replace.
import 'package:tandem/core/firebase/firebase_options.dart';

const String kEnv = String.fromEnvironment('ENV', defaultValue: 'dev');
const bool kUseEmulator = bool.fromEnvironment(
  'USE_EMULATOR',
  defaultValue: false,
);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  if (kUseEmulator) {
    const host = 'localhost';
    await FirebaseAuth.instance.useAuthEmulator(host, 9099);
    FirebaseFirestore.instance.useFirestoreEmulator(host, 8080);
    FirebaseFunctions.instanceFor(
      region: 'us-central1',
    ).useFunctionsEmulator(host, 5001);
    await FirebaseStorage.instance.useStorageEmulator(host, 9199);
  } else {
    const recaptchaKey = String.fromEnvironment('RECAPTCHA_SITE_KEY');
    if (recaptchaKey.isNotEmpty) {
      await FirebaseAppCheck.instance.activate(
        androidProvider: AndroidProvider.playIntegrity,
        appleProvider: AppleProvider.appAttest,
        webProvider: ReCaptchaEnterpriseProvider(recaptchaKey),
      );
    }
    // In debug mode without a key, skip App Check entirely.
    // Functions have enforceAppCheck: false for dev.
  }

  // Crashlytics: catch all Flutter and uncaught errors.
  if (!kDebugMode) {
    FlutterError.onError = (details) {
      // Forward to Crashlytics in production builds.
      // Avoid hard dep here to keep test compilation lightweight.
    };
  }

  runApp(const ProviderScope(child: TandemApp()));
}
