// Generated by FlutterFire CLI + manual patch.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
            'iOS Firebase options not yet configured. Run flutterfire configure.');
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZKkYwZ5PHEuW_jpkBAEF0i40O575nd4w',
    appId: '1:159067562109:web:113b72f1caf8cf4ff91114',
    messagingSenderId: '159067562109',
    projectId: 'tandem-ce3fd',
    authDomain: 'tandem-ce3fd.firebaseapp.com',
    storageBucket: 'tandem-ce3fd.firebasestorage.app',
    measurementId: 'G-FB7G2SG1PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKMIHn2084sTqly3wiRkiEUi5BjvSIAo',
    appId: '1:159067562109:android:11350ae743fa2d83f91114',
    messagingSenderId: '159067562109',
    projectId: 'tandem-ce3fd',
    storageBucket: 'tandem-ce3fd.firebasestorage.app',
  );
}
